[package]
name = "minipas-module"
version = "0.1.0"
edition = "2024"

[dependencies]
minipas-ast = { path = "../minipas-ast" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"

[dev-dependencies]
insta = "1.41"
